### ISSUE TITLE
Hi there !

### ISSUE THREAD

**Issue by RaZ0rr-Two** [booperlv/dots#1]
Recently, saw your gomove plugin. So, just wanted to look at your nvim dots. 

Wanted to say [nvim-compe](https://github.com/hrsh7th/nvim-compe) is deprecated and use [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) (same author) instead.

If you want you can look at mine [cmp/init.lua](https://github.com/RaZ0rr-Two/myNeovim/blob/main/nvim/lua/plugins/general/nvim-cmp/init.lua)

**Comment by booperlv** [comment]
Thanks for the heads up and reference! I'll make sure to change it in a few days, been too lazy to study how to configure it so the file you sent is a really big help. I'll close this issue when I set it up :)

**Comment by booperlv** [comment]
Just configured it! Forgot how fun configuring was sometimes :))
